name: CI - FlaskDevOpsDeploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpass
          POSTGRES_DB: devdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Repo dosyalarını çek
      uses: actions/checkout@v3

    - name: Python kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Gerekli kütüphaneleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.
        
    - name: PostgreSQL hazır mı kontrol et
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 && break
          echo "PostgreSQL hazır değil, bekleniyor..."
          sleep 3
        done   

    - name: Testleri çalıştır
      env:
        DB_HOST: localhost
        DB_NAME: devdb
        DB_USER: devuser
        DB_PASS: devpass
        DB_PORT: 5432
        PORT: 5000
      run: pytest

    - name: Deploy
      run: echo "✅ Uygulama başarıyla deploy edildi"
